### ISSUE TITLE
Better to use %APPDATA%\marks for %MARKSPATH%?

### ISSUE THREAD

**Issue by ProactiveServices** [fredericseiler/jump#1]
Since %APPDATA% is a more appropriate place to keep a user's program information, do you think it's worth using %APPDATA%\marks for the %MARKSPATH%?

I may be picky, but I find it irritating that my %USERPROFILE% gets increasingly cluttered with .appname folders that I don't need to see in my user files. I'd much rather that sort of data is hidden in %APPDATA%, and I believe this is closer to Windows convention.

I'm happy to make the changes and do a PR if you are open to the idea.

**Comment by fredericseiler** [comment]
Makes sense to me. Maybe it's even better to use `%LOCALAPPDATA%` than `%APPDATA%`, with the loss of XP support. But then again, who still uses XP nowadays...

Note that, in the meantime, you can easily override `%MARKPATH%` or `%HOME%` to whatever you want in the System Properties (user or system scope).

**Comment by ProactiveServices** [comment]
`%APPDATA%` on Vista+ points to `%USERPROFILE%\AppData\Roaming` which is used for application data that should "roam" to other computers; in Windows 8+ this is expanded to include the Microsoft Account cloud syncing. Rather than being obsoleted from Vista+, it's still in use but points to a different path.

`%LOCALAPPDATA%` is new to Vista+, and points to `%USERPROFILE%\AppData\Local` which is used for machine-specific application data. I'd suggest that in the case of jump, the roaming appdata is appropriate.

I'll pop over a PR in a bit. And get round to trying out jump :-P

**Comment by fredericseiler** [comment]
I suggested `%LOCALAPPDATA%` because I really think that marks shouldn't be shared between computers through your MS Account or AD/LDAP profile. You mark a local folder which maybe doesn't exist on another machine. Another case : "foo" on machine A points to `C:\foo`, and "foo" on machine B points to `C:\bar\foo`. I clearly don't want my marks to be synced and/or overriden between my laptop and my desktop.

**Comment by fredericseiler** [comment]
After some reflection, I decided to stay as close as possible to the original [ZSH plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/jump/jump.plugin.zsh#L9), but feel free to fork.
